import AboutSection from "@/components/AboutSection";
import ConfTrackSection from "@/components/ConfTrackSection";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import ImportantDateSection from "@/components/ImportantDateSection";
import Navbar from "@/components/Navbar";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>OPJU</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <Header />
        <AboutSection />
        <ImportantDateSection />
        <ConfTrackSection />
        <Footer />
      </main>
    </>
  );
}