import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import Head from "next/head";

import styles from "@/styles/style.module.css";

const Registration = () => {
  return (
    <div>
      <Head>
        <title>OPJU</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div>
        <div className="container my-5 pt-5">
          <h2 className="fw-semibold text-center">Registration</h2>
          <table className="table table-bordered mt-5">
            <thead>
              <tr>
                <th scope="col">Participants (Authors) Categories</th>
                <th scope="col" colSpan="2">
                  Registration Fee Including GST
                </th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <th scope="row"></th>
                <th scope="row">INR</th>
                <th scope="row">Euro</th>
              </tr>
              <tr>
                <td>Research Scholars (UG / PG / PhD)</td>
                <td>7000</td>
                <td>95</td>
              </tr>
              <tr>
                <td>Academicians / Researchers</td>
                <td>8000</td>
                <td>105</td>
              </tr>
              <tr>
                <td>Industry Persons</td>
                <td>10000</td>
                <td>120</td>
              </tr>
              <tr>
                <td>Listeners</td>
                <td>2000</td>
                <td>30</td>
              </tr>
            </tbody>
          </table>
          <div className="card">
            <div className="card-header">Account Details:</div>
            <ul class="list-group list-group-flush">
              <li class="list-group-item">A/C Name : OP Jindal University</li>
              <li class="list-group-item">A/c No. : 50200054124691</li>
              <li class="list-group-item">RTGS/NEFT IFSC : HDFC0001454</li>
              <li class="list-group-item">MICR : 496240002</li>
              <li class="list-group-item">Swift Code : HDFCINBBXXX</li>
            </ul>
          </div>
        </div>
        {/* <Footer /> */}
      </div>
    </div>
  );
};

export default Registration;
